# credentialFile - Path and filename for where credentials are stored
## credentialFile: /opt/webauthn_proxy/credentials.yml

# rpDisplayName - Display name of relying party
rpDisplayName: "Example, Inc."

# rpID - ID of the relying party, usually the domain the proxy and callers live under
rpID: example.com

# rpOrigins - Array of full origins used for accessing the proxy, including port if not 80/443
#rpOrigins:
#  - https://service.example.com

# serverAddress - Address the proxy server should listen on (usually 127.0.0.1 or 0.0.0.0)
## serverAddress: 127.0.0.1 

# serverPort - Port the proxy server should listen on
## serverPort: 8080

# sessionSoftTimeoutSeconds - Length of time logins are valid for, in seconds
## sessionSoftTimeoutSeconds: 28800

# sessionHardTimeoutSeconds - Max length of logged in session, as calls to /webauthn/auth reset the session timeout
## sessionHardTimeoutSeconds: 86400

# staticPath - Path on disk to static assets
## staticPath: /static/

# testMode - When set to 'true', users can authenticate immediately 
# after registering. Useful for testing, but generally not safe for production.
## testMode: false

# usernameRegex - Regex for validating usernames
# The following regex will allow usernames with uppercase, lowercase, digits, or "-.@" ...
# Basically, email addresses
## usernameRegex: ^[A-Za-z0-9\-\_\.\@]+$